BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Agents" (
	"AgentID"	INTEGER,
	"AgentName"	TEXT NOT NULL,
	"AgentEmail"	TEXT,
	"Token"	TEXT NOT NULL UNIQUE,
	"Active"	BOOLEAN DEFAULT 1,
	PRIMARY KEY("AgentID")
);
COMMIT;
